# Site settings
title: TeamSkorpz - Entertainment Hub!
description: Unlock Limitless Entertainment, Premium Accounts, Free IPTV, Elevate Your Viewing, Embrace the Future!
keywords: Video On Demand, HD Streaming, IPTV, Premium Accounts, Free IPTV, Online Entertainment, Streaming Services, Subscription Plans, Digital Content, Live TV
author: Mr Skorpz
baseurl: "/teamskorpz.github.io" # the subpath of your site, e.g. /blog/
url: "https://teamskorpz.github.io/" # the base hostname & protocol for your site