# Site settings
title: TeamSkorpz - Entertainment Hub!
description: Unlock Limitless Entertainment Premium Accounts Free IPTV Elevate Your Viewing Embrace the Future!
keywords: HD Streaming, IPTV, Premium Accounts, Free IPTV, Streaming Services, Live TV
author: Mr Skorpz
baseurl: "/teamskorpz.github.io" # the subpath of your site, e.g. /blog/
url: "https://teamskorpz.github.io/" # the base hostname & protocol for your site