# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Skorpz Limited
# Description of the Site
description: Premium Streams, Free Dreams, Your Ultimate IPTV Destination!
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: IPTV, Streaming, Free IPTV, Live TV, HD Streaming, Subscription Plans,
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: skorpz.limited@gmail.com
facebook_username: /
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: /
github_username:  TeamSkorpz
youtube_channel_id: /
telegram_username: Teamskorpz
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: G-17L90DSZB6

# Disqus
disqus-shortname: skorpzincjamie

# Name of the Author
author-name: Mr Skorpz
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Unleash Entertainment, Elevate Experience, Your Gateway to Limitless Entertainment with Premium Accounts and Free IPTV, Elevate Your Viewing, Embrace the Future!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/teamskorpz

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
