# Site settings
title: TeamSkorpz - Entertainment Hub
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Skorpz
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "teamskorpz.github.io" # the base hostname & protocol for your site
