# Site settings
title: TeamSkorpz
description: Modern-Blog A Elegant template for Jekyll
keywords: Skorpz, TeamSkorpz, Free Apps
author: BusyGuy
baseurl: "Jekyll_modern-blog" # the subpath of your site, e.g. /blog/
url: "https://teamskorpz.github.io/" # the base hostname & protocol for your site
